version: '3.3'

services:
  db:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    build: ../backend
    restart: always
    volumes:
      - data_value:/app/data/
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    build:
      context: ../frontend
    restart: always
    command: sh -c "cp -r /react/build/* /shared && tail -f /dev/null"
    volumes:
      - react_build:/shared


  nginx:
    image: nginx:1.19.3
    restart: always
    ports:
      - "9001:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/
      - react_build:/var/www/react
    depends_on:
      - frontend
      - web

volumes:
  static_value:
  media_value:
  data_value:
  react_build: